### ISSUE TITLE
Example logfile?

### ISSUE THREAD

**Issue by IHateNameStealers** [yoxcu/vdla#1]
I know. It's now 2022, and you last update was 2 years ago, so this might be a problem.
I've tested your website version, and the one here from GitHub with one of my official VESC logfiles, but with no luck.

Problem is (I think) that the new VESC exported files have way more info, and have I guess a different structure.
As I'm creating my own exported VESC/GPS files (using Arduino and a can bus), I would love to give your tool a go and see how it looks.

Do you maybe have a working example logfile for me so I can have a look t it?

Thank you.

**Comment by yoxcu** [comment]
here you go!
[2018-06-24_14-00-59_Link_esc_Data.csv](https://github.com/yoxcu/vdla/files/10298506/2018-06-24_14-00-59_Link_esc_Data.csv)

also this data was recorded via the Ackmaniac FW and APP on a VESC4/FOCBOX

you can also test it on https://yoxcu.de/vdla

Let me know if you have any other questions!

**Comment by IHateNameStealers** [comment]
perfect. Thank you
